### ISSUE TITLE
Add info about how to access the available trigger context variables in the Wiki?

### ISSUE THREAD

**Issue by mfishco** [Coding-With-The-Force/Salesforce-Separation-Of-Concerns-And-The-Apex-Common-Library#1]
Was trying how to access Trigger.new, Trigger.old, etc... and was looking in section 11.  Are they somewhere else?  Or maybe info regarding this could be added somewhere?

**Comment by Coding-With-The-Force** [comment]
I have updated that section to include information on that! Thanks for bringing that up! Hopefully that helps!

**Comment by mfishco** [comment]
Thanks for addressing my issue so quickly!  You are the bestest!
