### ISSUE TITLE
Test class

### ISSUE THREAD

**Issue by Jqda0** [Coding-With-The-Force/Salesforce-Separation-Of-Concerns-And-The-Apex-Common-Library#2]
It would be really helpful to also see sample test classes!

**Comment by Coding-With-The-Force** [comment]
Hey there, I do have one example test class in the repo here, but if you'd like to see something more specific please let me know! https://github.com/Coding-With-The-Force/Salesforce-Separation-Of-Concerns-And-The-Apex-Common-Library/blob/main/src/classes/Apex_Common_Abstract_Task_Factory_Pattern_Example/Task_Service_Impl_Test.cls
